/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OcrIndexRouteImport } from './routes/_ocr/index'
import { Route as OcrPerformanceRouteImport } from './routes/_ocr/performance'

const OcrIndexRoute = OcrIndexRouteImport.update({
  id: '/_ocr/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrPerformanceRoute = OcrPerformanceRouteImport.update({
  id: '/_ocr/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/performance': typeof OcrPerformanceRoute
  '/': typeof OcrIndexRoute
}
export interface FileRoutesByTo {
  '/performance': typeof OcrPerformanceRoute
  '/': typeof OcrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ocr/performance': typeof OcrPerformanceRoute
  '/_ocr/': typeof OcrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/performance' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/performance' | '/'
  id: '__root__' | '/_ocr/performance' | '/_ocr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OcrPerformanceRoute: typeof OcrPerformanceRoute
  OcrIndexRoute: typeof OcrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ocr/': {
      id: '/_ocr/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OcrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ocr/performance': {
      id: '/_ocr/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof OcrPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  OcrPerformanceRoute: OcrPerformanceRoute,
  OcrIndexRoute: OcrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
